#[all:vars]
#host_user: cosysoft
#host_pass: remote236

[docker_hosts]
localhost ansible_connecton=local ansible_ssh_user=msancho

[serversHV]
server-cosysoft ansible_ssh_host=192.168.63.2 ansible_ssh_port=22 ansible_ssh_user=cosysoft
JackDaniels ansible_ssh_host=192.168.63.3 ansible_ssh_user=cosysoft
cs-hsu-backup4 ansible_ssh_host=192.168.63.4 ansible_ssh_user=cosysoft

[web_route_gw]
JeambBeam ansible_ssh_host=85.90.247.159 ansible_ssh_port=2222 ansible_ssh_user=root nat_dev=eth0

localhost ansible_connecton=local ansible_ssh_user=msancho

[test_client]
test-ubuntu-docker
test-vdd-test

[test_gw]
test-vsckvm-gw
test-gw
