#[all:vars]
#host_user: cosysoft
#host_pass: 

[docker_hosts]
localhost ansible_connection=local 
#ansible_ssh_user=mdm_admin
mdm02.elcom.loc
mdmdb01.elcom.loc

[rke-hosts]
localhost ansible_connection=local
#ansible_ssh_user=mdm_admin
mdm02.elcom.loc
