- hosts: docker_hosts
  tasks:
    - name: remove docer
      apt: 
        name: docker docker-engine docker.io containerd runc 
        state: absent
        purge: yes
      become: true
#       remove docker

    - name: install enveroment docker
      apt: 
        name: 
            - apt-transport-https 
            - ca-certificates 
            - curl 
            - gnupg-agent 
            - software-properties-common
        state: present 
        update_cache: yes
      become: yes
#       install enveroent for docker
    
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

# Add specified repository into sources list.
    - apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}  stable
        state: present
      become: true

    - name: install docker
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      become: true

    - name: Copy config daemon
      copy:
        src: ansible-file/daemon.json
        dest: /etc/docker/daemon.json
        group: root
        owner: root
      become: true
      tags: config_docker

    - name: Make sure a service is running
      systemd:
        name: docker
        state: restarted
      become: true
      tags: config_docker
#    - name: Set owner config file 
#      file: 
#               path: /tmp/hosts
#                  mode: '0777'  
    - name: Add groups 'docker' the user 'cosysoft'  
      user:
        name: cosysoft
        groups: docker
        append: yes
      become: true
      tags: usermod

    - name: test docker
      command: docker run --name hello_world hello-world
      become: yes
      become_user: cosysoft
      tags: run_test_docker

    - name: clear for docker
      command: docker container rm hello_world
      become: yes
      become_user: cosysoft
      tags: run_test_docker

    - name: clear for docker iamge
      command: docker image rm hello-world:latest
      become: yes
      become_user: cosysoft
      tags: run_test_docker
